# Generated by Django 2.0.7 on 2019-09-12 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
