# Generated by Django 2.0.7 on 2019-07-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20190709_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image_preview',
            field=models.FileField(upload_to=''),
        ),
    ]
