# Generated by Django 2.0.7 on 2019-07-10 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_remove_project_image_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='data',
            field=models.DateField(null=True),
        ),
    ]
