# Generated by Django 2.0.7 on 2019-07-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_project_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='data',
            field=models.DateField(null=0.00024888003982080636),
        ),
    ]
