# Generated by Django 2.0.7 on 2019-07-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20190710_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
